version: '3'
services:

  busybox:
    hostname: busybox
    image: "busybox:latest"
    restart: always
    command: sh -c "while true; do date; sleep 60; done"
    links:
      - influxdb2
    networks:
      - sound_meter

  nsrt-mk3-dev-logger:
    hostname: nsrt-mk3-dev-logger
    image: "dcwangmit01/nsrt-mk3-dev-logger:0.3.0"
    restart: always
    devices:
      - ${LOCAL_NSRT_DEVICE}
    volumes:
      # Mount for data directory
      - ./volumes/nsrt-mk3-dev-logger/measurements/:/measurements/

  influxdb2:
    hostname: influxdb2
    # https://hub.docker.com/_/influxdb
    image: "influxdb:2.7"
    volumes:
      # Mount for influxdb data directory
      - ./volumes/influxdb2/var/lib/influxdb2/:/var/lib/influxdb2/
      # Mount for influxdb configuration
      - ./volumes/influxdb2/etc/influxdb/:/etc/influxdb/
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
    restart: always
    networks:
      - sound_meter

  telegraf:
    hostname: telegraf
    # https://hub.docker.com/_/telegraf
    image: "telegraf:1.27"
    volumes:
      # Mount for telegraf configuration
      - ./volumes/telegraf/etc/telegraf/:/etc/telegraf/
      - ./volumes/nsrt-mk3-dev-logger/measurements/:/measurements/
    links:
      - influxdb2
    depends_on:
      - influxdb2
    environment:
      - INFLUX_TOKEN=${INFLUXDB2_TOKEN}
    restart: always
    networks:
      - sound_meter

  grafana:
    hostname: grafana
    # https://hub.docker.com/r/grafana/grafana
    image: "grafana/grafana:9.5.3"
    volumes:
      # Mount for grafana configuration
      - ./volumes/grafana/etc/grafana/:/etc/grafana/
      - ./volumes/grafana/var/lib/grafana/:/var/lib/grafana/
    environment:
      - GF_SECURITY_ADMIN_USER=${INFLUXDB2_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${INFLUXDB2_PASSWORD}
      - GF_INSTALL_PLUGINS=marcusolsson-hourly-heatmap-panel
    links:
      - influxdb2
    depends_on:
      - influxdb2
    ports:
      - "3000:3000"
    user: "0"
    restart: always
    networks:
      - sound_meter

  nginx:
    container_name: nginx
    image: nginx:alpine
    networks:
      - sound_meter
    volumes:
      - ./conf/nginx/htpasswd:/etc/nginx/htpasswd:ro
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - ./volumes/certbot/conf:/etc/letsencrypt
      - ./volumes/certbot/www:/var/www/certbot
      - ./volumes/nginx/web:/var/www
    ports:
      - 80:80
      - 443:443
    restart: always
    command: /bin/sh -c "while :; do sleep 24h & wait $${!}; nginx -s reload; done & nginx -g 'daemon off;'"
    depends_on:
      - grafana

  certbot:
    container_name: certbot
    image: certbot/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot --webroot-path /var/www/certbot; sleep 12h & wait $${!}; done;"
    networks:
      - sound_meter
    volumes:
      - ./volumes/certbot/conf:/etc/letsencrypt
      - ./volumes/certbot/www:/var/www/certbot
    restart: always
    depends_on:
      - nginx

networks:
  sound_meter:
