{
 "title": "Decibel Measurements",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Weighted dbC - Individual Raw Samples at 1s Period",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"microphone\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"decibels\")\n  |> filter(fn: (r) => r[\"_field\"] == \"weighted_level\")\n  |> yield(name: \"raw\")"
    }
   ]
  },
  {
   "title": "Weighted dbC - Mean (Line Chart)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"microphone\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"decibels\")\n  |> filter(fn: (r) => r[\"_field\"] == \"weighted_level\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Weighted dbC - Mean (Heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"microphone\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"decibels\")\n  |> filter(fn: (r) => r[\"_field\"] == \"weighted_level\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Weighted dBC - Mean (Daily Hourly Heat Map)",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: \"microphone\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"decibels\")\n  |> filter(fn: (r) => r[\"_field\"] == \"weighted_level\")\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Weighted dbC - Max, Mean, Min",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"microphone\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"decibels\")\n  |> filter(fn: (r) => r[\"_field\"] == \"weighted_level\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> yield(name: \"max\")"
    },
    {
     "query": "from(bucket: \"microphone\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"decibels\")\n  |> filter(fn: (r) => r[\"_field\"] == \"weighted_level\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"microphone\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"decibels\")\n  |> filter(fn: (r) => r[\"_field\"] == \"weighted_level\")\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\n  |> yield(name: \"min\")"
    }
   ]
  }
 ]
}